---


consul_profile_path: "/etc/profile.d/consul.sh"
private_ip: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
retry_join_ips: "{{ play_hosts  | difference(inventory_hostname) }}"
