---
- block :
  - name: "stoping soil service if running"
    shell: "systemctl stop soil"
    ignore_errors: true
  - name: "cleaning up past setup directories"
    file:
      path: "{{ item }}"
      state: absent
    with_items:
        - '{{ soil_data_path }}/'
        - '{{ soil_user_home_path }}'
  - name: "making sure soil config directories are present on remote"
    file:
      path: "{{ item }}"
      state: directory
      group : "root"
      owner: "root"
      mode: '0755'
    with_items:
        - '{{ soil_user_home_path }}'
        - '{{ soil_data_path }}'
  become: yes
