---
- block:
  - name: create temporary build directory
    tempfile:
      state: directory
      suffix: build
    register: build_dir
  - block:
    - name: Assert variables
      assert:
        that:
          - build_dir.path is defined and build_dir.path | length > 0
    - stat:
        path: "{{ build_dir.path }}"
      register: "build_dir_stat"
    - name: making sure build directory exists
      fail:
        msg: >
          cannot build soil as build directory at
          '{{ build_dir.path }} does not exists'.
      when:
          - not build_dir_stat.stat.exists
  # [ NOTE ] docker module is not working
  # - name: "build soil in container"
  #   docker_container:
  #     name: soil-builder
  #     image: golang:alpine
  #     recreate: yes
  #     working_dir: "/go/src/{{soil_repo}}"
  #     env:
        # GO111MODULE: "off"
        # CGO_ENABLED: "0"
        # CGO_LDFLAGS: "-s -w -extldflags '-static'"
  #     command: |
  #       set -euxo pipefail ;
  #       apk add git ;
  #       git clone https://{{soil_repo}} /go/src/{{soil_repo}} ;
  #       go get -v -d ./... ;
  #       go build -o /go/bin/soil command/soil
  #     volumes:
  #       # - "build_dir.path:/go/bin"
  #       - "/tmp/soil-build:/go/bin"
  # - name: "remove soil builder container"
  #   docker_container:
  #     name: soil-builder
  #     state: absent
  - name: build soil in container
    shell: |
      docker run -v "/tmp/soil-build:/tmp/bin:z" --entrypoint "" --rm -i fjolsvin/vscode-golang-alpine /bin/bash -c 'go env -w "GO111MODULE=off" &&  mkdir -p ~/go/src/github.com/akaspin/ && git clone https://github.com/akaspin/soil.git ~/go/src/github.com/akaspin/soil && cd ~/go/src/github.com/akaspin/soil && go build -o /tmp/soil ./command/soil && sudo mv /tmp/soil /tmp/bin/'
    args:
      creates: "/tmp/soil-build/soil"
    become: yes
    delegate_to: localhost
    run_once: true
  become: yes
