---
- block :
  - name: "Ensure group 'soil' exists"
    group:
      name: soil
      state: present
  - name: "Ensure system user 'soil' exists"
    user:
      state: present
      shell: /bin/false
      system: yes
      name: "soil"
      group: "soil"
      home: "{{ soil_user_home_path }}"
      groups: docker,soil

  - name: "making sure required directories are present on remote and have proper permissions"
    file:
      path: "{{ item }}"
      state: directory
      group : "soil"
      owner: "soil"
      mode: '0755'
    with_items:
        - '{{ soil_data_path }}'
        - '{{ soil_user_home_path }}'
  become: yes
