---

- name: Assert variables
  assert:
    that:
      - systemd_unit_directory is defined and systemd_unit_directory | length > 0
      - soil_config_path is defined and soil_config_path | length > 0
      - soil_port is defined and soil_port > 0
