---
- block :
  - name: "making sure soil config directory are present on remote and have proper permissions"
    file:
      path: "{{ item }}"
      state: directory
      group : "soil"
      owner: "soil"
      mode: '0755'
    with_items:
        - '{{ soil_config_path }}'
  - find:
      paths: ["{{ role_path }}/templates/config"]
      file_type: file
      use_regex: yes
      patterns: ['^.*\.hcl\.j2$']
    register: "hcl_config_filelist"
    run_once: true
    delegate_to: localhost
  - set_fact:
      hcl_config_filelist: >
        {{
          hcl_config_filelist.files |
          map(attribute='path')  |
          list |
          regex_replace(role_path + '/templates/config.*?/','') |
          regex_replace('\.j2','')
        }}
  - name: "uploading soil config files"
    template:
      src: "config/{{ item }}.j2"
      dest: "{{ soil_config_path }}/{{ item }}"
      force: yes
      decrypt: yes
    loop: "{{ hcl_config_filelist }}"
  - name: "changing all single quotes to double quotes in soil conf files"
    shell: |
      sed -i "s/'/\"/g" {{ soil_config_path }}/*.hcl
  become: yes
