---
- block :
  - name: "making sure systemd user service directory is present on remote"
    file:
      path: "{{ item }}"
      state: directory
      group : "root"
      owner: "root"
      mode: '0755'
    with_items:
        - '{{ systemd_unit_directory }}'
  - find:
      paths: ["{{ soil_user_home_path }}"]
      file_type: file
      use_regex: yes
      patterns: ['^.*\.hcl$']
    register: "hcl_config_filelist"
    run_once: true
  - debug:
      var: hcl_config_filelist

  - set_fact:
      hcl_config_filelist: >
        {{
          hcl_config_filelist.files |
          map(attribute='path')  |
          list
        }}
  - name: "uploading soil systemd service file"
    template:
      src: "service/soil.service.j2"
      dest: "{{ systemd_unit_directory }}/soil.service"
      force: yes
      decrypt: yes
  - block:
    - name: "reloading systemctl"
      command: "systemctl daemon-reload"
    - name: "making sure soil service runs at startup"
      command: "systemctl enable --now soil"
    - name: "stoping soil service if running"
      command: "systemctl stop soil"
    - name: "starting soil service"
      command: "systemctl start soil"
    - pause:
        seconds: 30
        prompt: waiting for soil server to start and become available
    - name: "make sure soil service is really running"
      command: "systemctl is-active soil"
  become: yes
