---
- block:
  # - import_tasks:  "00-asserts.yml"
  # - import_tasks:  "03-ufw.yml"
  # - import_tasks:  "04-config-files.yml"
  # - import_tasks:  "05-pod-files.yml"
  - import_tasks:  "06-systemd-units.yml"
