---

- stat:
    path: "{{ certificate_root_dir }}/consul/{{ inventory_hostname }}/server.pem.enc"
  register: "server_pem_enc"
- stat:
    path: "{{ certificate_root_dir }}/consul/{{ inventory_hostname }}/server-key.pem.enc"
  register: "server_key_pem_enc"
- stat:
    path: "{{ certificate_root_dir }}/consul/{{ inventory_hostname }}/server.csr.enc"
  register: "server_csr_enc"
- block:
  - name : "removing leftover consul server 'server.pem.enc'"
    file:
      path: "{{ certificate_root_dir }}/consul/{{ inventory_hostname }}/server.pem.enc"
      state: absent
    when:
      - server_pem_enc.stat.exists
  - name : "removing leftover consul server 'server-key.pem.enc'"
    file:
      path: "{{ certificate_root_dir }}/consul/{{ inventory_hostname }}/server-key.pem.enc"
      state: absent
    when:
      - server_key_pem_enc.stat.exists
  - name : "removing leftover consul server 'server.csr.enc'"
    file:
      path: "{{ certificate_root_dir }}/consul/{{ inventory_hostname }}/server.csr.enc"
      state: absent
    when:
      - server_csr_enc.stat.exists
  - name: "Generating consul server certificates for '{{ inventory_hostname }}'"
    # shell: "echo '{\"key\":{\"algo\":\"rsa\",\"size\":2048}}' | cfssl gencert -ca={{ certificate_root_dir }}/consul/ca.pem -ca-key={{ certificate_root_dir }}/consul/ca-key.pem -config={{ cfssl_config_path }} -hostname='server.dc1.consul,{{ inventory_hostname }},{{ private_ip }},localhost,127.0.0.1' - | cfssljson -bare server"
    shell: "consul tls cert create -ca {{ certificate_root_dir }}/consul/ca.pem -key={{ certificate_root_dir }}/consul/ca-key.pem -server && mv dc1-server-consul-0-key.pem server-key.pem && mv dc1-server-consul-0.pem server.pem"
    args:
      chdir: "{{ certificate_root_dir }}/consul/{{ inventory_hostname }}"

  when: >
    ca_pem_enc.stat.exists == False or
    ca_key_pem_enc.stat.exists == False or
    ca_csr_enc.stat.exists == False
