---
cfssl_version: "{{ lookup('env','CFSSL_cfssl_version') | default('1.4.1', true) }}"
cfssl_checksum_url: "https://github.com/cloudflare/cfssl/releases/download/v{{ cfssl_version }}/cfssl_{{ cfssl_version }}_checksums.txt"
