---
- block:
  - name: "uploading consul server ca"
    copy:
      src: "{{ certificate_root_dir }}/consul/ca.pem.enc"
      dest: "{{ consul_user_home_path }}/ca.pem"
      force: yes
      decrypt: yes
  - name: "uploading consul server certificates "
    copy:
      src: "{{ certificate_root_dir }}/consul/{{ inventory_hostname }}/{{ item }}.enc"
      dest: "{{ consul_user_home_path }}/{{ item }}"
      force: yes
      decrypt: yes
    loop: ['server.pem','server-key.pem','cli.pem','cli-key.pem']
  become: yes
