- name: Check OS compatibility
  fail:
    msg: "{{ ansible_facts['os_family'] }} is not currently supported by this role."
  when:
    - ansible_facts['os_family'] not in ['Debian']
- name: Assert variables
  assert:
    that:
      - docker_repository_gpg_url is defined
      - docker_linux_repository_source is defined
