- become: true
  block:
    - import_tasks: 00-asserts.yml
    - import_tasks: 01-initialize.yml
    - include_tasks: installer.yml
      loop:
        - name: ca-certificates
        - name: curl
        - name: jq
        - name: wget
        - name: sudo
        - name: unzip
        - name: apt-transport-https
        - name: ca-certificates
        - name: gnupg2
        - name: iptables
        - name: ufw
      name: 'Installing base dependencies'
